apiVersion: apps/v1
kind: Deployment
metadata:
  name: craig
spec:
  selector:
    matchLabels:
      app: craig
  template:
    metadata:
      labels:
        app: craig
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "otel-operator/instrumentation-grpc"
    spec:
      containers:
      - name: craig
        image: 992382534381.dkr.ecr.us-east-1.amazonaws.com/cs-prod-craig-bot:e4f5133
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
        envFrom:
          - secretRef:
              name: craig-secrets
          - secretRef:
              name: postgresql-secrets
        env:
          - name: DATABASE_URL
            value: "postgresql://craig:$(pg-user-password)@app-craig-bot-postgresql:5432/craig?schema=public"
          - name: REDIS_HOST
            value: app-craig-bot-redis-master
          - name: REDIS_PORT 
            value: "6379"
          - name: API_HOMEPAGE
            value: "https://craig-api-us-east-1.cs.web3factory.consensys.net"
          - name: API_HOST
            value: "0.0.0.0"
          - name: ENNUIZEL_BASE
            value: "https://ez.craig.horse/"
          - name: NODE_ENV
            value: 'production'
        ports:
          - name: app
            containerPort: 3000
            protocol: TCP
          - name: api
            containerPort: 5029
            protocol: TCP
