---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: craig-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: craig-secrets
    creationPolicy: Owner
  data:
    - secretKey: DISCORD_BOT_TOKEN
      remoteRef:
        key: craig_secrets
        property: DISCORD_BOT_TOKEN
    - secretKey: DISCORD_APP_ID
      remoteRef:
        key: craig_secrets
        property: DISCORD_APP_ID
    - secretKey: CLIENT_ID
      remoteRef:
        key: craig_secrets
        property: CLIENT_ID
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: craig_secrets
        property: CLIENT_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: default
    kind: ClusterSecretStore
  target:
    name: postgresql-secrets
    creationPolicy: Owner
  data:
    - secretKey: pg-admin-password
      remoteRef:
        key: craig_secrets
        property: pg-admin-password
    - secretKey: pg-user-password
      remoteRef:
        key: craig_secrets
        property: pg-user-password
