apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-craig-bot
  namespace: cs
spec:
  destination:
    name: cs-prod-us-east-1
    namespace: craig-bot
  project: apps-cs-prod
  sources:
    - repoURL: https://github.com/ConsenSys/w3f-craig.git
      path: deployment/app
      targetRevision: master
    - chart: postgresql
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 16.3.5
      helm:
        values:  |
          primary:
            resourcesPreset: small
          auth:
            existingSecret: postgresql-secrets
            database: craig
            username: craig
            secretKeys:
              adminPasswordKey: pg-admin-password
              userPasswordKey: pg-user-password
    - chart: redis
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 20.6.1
      helm:
        values:  |
          master:
            resourcesPreset: small
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
