apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-craig-bot
  namespace: cs
spec:
  project: infra-cs-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: cs-prod
  source:
    repoURL: https://github.com/ConsenSys/w3f-craig.git
    path: deployment/infra
    targetRevision: master