name: build docker images

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  release:
    name: Create Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            992382534381.dkr.ecr.us-east-1.amazonaws.com/cs-prod-craig-bot
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=false
            type=raw,value={{sha}}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::992382534381:role/ecr-push-cs-prod-craig-bot
          aws-region: us-east-1
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 992382534381.dkr.ecr.us-east-1.amazonaws.com
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}